#!/usr/bin/env python3
"""Inverse graph design: recover edge weights from a target low spectrum."""
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
import sft


OUT = os.path.join(os.path.dirname(__file__), "reports", "inverse_graph_design.md")
os.makedirs(os.path.dirname(OUT), exist_ok=True)

N = 12
adj = sft.graph_gen.path_graph(N)
fam = sft.families.graph_laplacian(adj)
rng = np.random.default_rng(42)
true_k = 0.08 * rng.standard_normal(fam.M)
target = fam.spectrum(true_k, n_eigs=6)

t0 = time.perf_counter()
result = fam.inverse(target, n_eigs=6, steps=20, alpha=0.5, refresh_every=4, method="trust")
elapsed = (time.perf_counter() - t0) * 1000
recovered = fam.spectrum(result.k, n_eigs=6)
spectral_err = float(np.max(np.abs(recovered - target)))
param_err = float(np.linalg.norm(result.k - true_k))

md = f"""# Inverse Graph Design

Task: perturb path-graph edge weights so the first 6 Laplacian eigenvalues hit
a target spectrum.

| Metric | Value |
|--------|------:|
| Nodes | {N} |
| Edges / parameters | {fam.M} |
| Controlled modes | 6 |
| Spectral error | {spectral_err:.3e} |
| Parameter L2 error | {param_err:.3e} |
| Isospectral dimension | {fam.isospectral_dimension()} |
| Method | {result.method} |
| Refreshes | {result.n_refresh} |
| Eigensolves | {result.eigh_count} |
| Runtime | {elapsed:.1f}ms |

The inverse is intentionally spectral: if `ker(W)` is non-empty, different edge
weight vectors can produce nearly identical low-mode spectra.

Generated by `demo_inverse_graph_design.py` on {time.strftime('%Y-%m-%d %H:%M')}.
"""

with open(OUT, "w") as f:
    f.write(md)
print(f"✓ inverse_graph_design.md written — spectral_err={spectral_err:.2e}, ghosts={fam.isospectral_dimension()}")
