#!/usr/bin/env python3
"""Generate independent SFT core verification reports."""
from __future__ import annotations

import argparse
import json
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
import sft


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate SFT independent verification reports.")
    parser.add_argument(
        "--out-dir",
        default=os.path.join(os.path.dirname(__file__), "reports"),
        help="Directory for markdown/json reports.",
    )
    args = parser.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    t0 = time.perf_counter()
    results = sft.verify.run_core_verification_suite()
    payload = sft.verify.verification_report_jsonable(results)
    payload["elapsed_ms"] = (time.perf_counter() - t0) * 1000.0

    md = sft.verify.verification_report_markdown(results)
    md += f"\nGenerated by `demo_verification_report.py` in {payload['elapsed_ms']:.1f}ms.\n"

    md_path = os.path.join(args.out_dir, "independent_verification.md")
    json_path = os.path.join(args.out_dir, "independent_verification.json")
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md)
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, sort_keys=True)

    print(
        "independent verification written: "
        f"{payload['passed']}/{payload['total']} passed, "
        f"markdown={md_path}, json={json_path}"
    )


if __name__ == "__main__":
    main()
