#!/usr/bin/env python3
"""Quantum exceptional point demo: square-root branch and EP atlas."""
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
import sft


OUT = os.path.join(os.path.dirname(__file__), "reports", "quantum_exceptional_point.md")
os.makedirs(os.path.dirname(OUT), exist_ok=True)

fam = sft.physics.exceptional_point_2x2().family()
loop = [
    np.array([0.25 * np.cos(t), 0.25 * np.sin(t)])
    for t in np.linspace(0, 2 * np.pi, 100)
]
t0 = time.perf_counter()
summary = sft.topology.complex_monodromy(fam, loop)
atlas = sft.topology.exceptional_point_atlas(fam, grid_resolution=31, k_range=(-0.5, 0.5), threshold=1e-8)
elapsed = (time.perf_counter() - t0) * 1000

winding = summary["windings"][(0, 1)]
best = atlas["candidates"][0]

md = f"""# Quantum Exceptional Point

Model: `A(z) = [[0, 1], [z, 0]]`, where `z = k0 + i*k1`.

## Result

| Metric | Value |
|--------|------:|
| Loop points | {len(loop)} |
| Gap winding | {winding:.3f} |
| Atlas min gap | {atlas['min_gap']:.3e} |
| Best candidate k | [{best['k'][0]:.3f}, {best['k'][1]:.3f}] |
| Coalescence score | {best['coalescence']:.3f} |
| Runtime | {elapsed:.1f}ms |

The half-integer winding is the numerical signature of a square-root
exceptional point: one loop around the branch point exchanges the two spectral
sheets.

Generated by `demo_quantum_ep.py` on {time.strftime('%Y-%m-%d %H:%M')}.
"""

with open(OUT, "w") as f:
    f.write(md)
print(f"✓ quantum_exceptional_point.md written — winding={winding:.3f}, min_gap={atlas['min_gap']:.1e}")
