#!/usr/bin/env python3
"""SFT load test — all 7 available adapters stress-tested."""
import sys, os, time
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
import numpy as np
import sft

OUT = os.path.join(os.path.dirname(__file__), "reports", "benchmark_adapters.md")

rng = np.random.default_rng(42)

# ── Audio ──
t0 = time.perf_counter()
audio = sft.audio(rng.standard_normal(44100 * 3), sample_rate=44100, n_bands=16)
audio_t = (time.perf_counter() - t0) * 1000

# ── Image ──
t0 = time.perf_counter()
img = sft.image(rng.standard_normal((128, 128)), patch_size=8, n_regions=16)
img_t = (time.perf_counter() - t0) * 1000

# ── Graph ──
V = 200; adj = (np.triu(rng.random((V, V)) < 0.1, 1)).astype(np.float64); adj += adj.T
t0 = time.perf_counter()
graph = sft.graph(adj)
graph_t = (time.perf_counter() - t0) * 1000

# ── Text ──
words = ["the cat sat on the mat", "the dog ran fast", "cat dog chase bird",
         "bird flew high", "fast cat bird tree", "tree green tall"]
t0 = time.perf_counter()
text = sft.text(words, max_words=20)
text_t = (time.perf_counter() - t0) * 1000

# ── Timeseries ──
t0 = time.perf_counter()
ts = sft.timeseries(rng.standard_normal(500), window_len=50)
ts_t = (time.perf_counter() - t0) * 1000

# ── Video ──
t0 = time.perf_counter()
video = sft.video(rng.standard_normal((30, 64, 64, 3)).astype(np.float32))
video_t = (time.perf_counter() - t0) * 1000

# ── Voxel ──
t0 = time.perf_counter()
voxel = sft.voxel(rng.standard_normal((32, 32, 32)))
voxel_t = (time.perf_counter() - t0) * 1000

# ── PointCloud ──
t0 = time.perf_counter()
pc = sft.pointcloud(rng.standard_normal((500, 3)), k=15)
pc_t = (time.perf_counter() - t0) * 1000

# ── Molecular ──
t0 = time.perf_counter()
mol = sft.molecular(
    rng.standard_normal((20, 3)),
    np.tile(['C', 'H', 'O', 'N'], 5)[:20],
    [(i, (i+1)%20) for i in range(20)]
)
mol_t = (time.perf_counter() - t0) * 1000

# ── Financial ──
t0 = time.perf_counter()
fin = sft.financial(rng.standard_normal((252, 30)))
fin_t = (time.perf_counter() - t0) * 1000

# ── Tabular ──
t0 = time.perf_counter()
tab = sft.tabular(rng.standard_normal((500, 20)))
tab_t = (time.perf_counter() - t0) * 1000

# ── Mesh ──
t0 = time.perf_counter()
vertices = rng.standard_normal((50, 3))
faces = rng.integers(0, 50, (40, 3))
mesh = sft.mesh(vertices, faces)
mesh_t = (time.perf_counter() - t0) * 1000

md = f"""# SFT Adapters — Load Test Across All 12 Domains

Every adapter: raw data → OperatorFamily in one call.

---

## Results

| Adapter | Input | Build | N | M | complexity | rank(W) |
|---------|-------|:---:|:---:|:---:|:---:|:---:|
| Audio | 132300 samples, 16 bands | {audio_t:.0f}ms | {audio.family.N} | {audio.family.M} | {audio.complexity:.3f} | {audio.rank} |
| Image | 128×128, patch=8, 16 regions | {img_t:.0f}ms | {img.family.N} | {img.family.M} | {img.complexity:.3f} | {img.rank} |
| Graph | V={V}, E={int(adj.sum()//2)} | {graph_t:.0f}ms | {graph.family.N} | {graph.family.M} | {graph.complexity:.3f} | {graph.rank} |
| Text | 6 docs, vocab=18 | {text_t:.0f}ms | {text.family.N} | {text.family.M} | {text.complexity:.3f} | {text.rank} |
| Timeseries | 500 pts, window=50 | {ts_t:.0f}ms | {ts.family.N} | {ts.family.M} | {ts.complexity:.3f} | {ts.rank} |
| Video | 30 frames, 64×64 | {video_t:.0f}ms | {video.family.N} | {video.family.M} | {video.complexity:.3f} | {video.rank} |
| Voxel | 32³ | {voxel_t:.0f}ms | {voxel.family.N} | {voxel.family.M} | {voxel.complexity:.3f} | {voxel.rank} |
| PointCloud | N=500, k=15 | {pc_t:.0f}ms | {pc.family.N} | {pc.family.M} | {pc.complexity:.3f} | {pc.rank} |
| Molecular | 20 atoms, 20 bonds | {mol_t:.0f}ms | {mol.family.N} | {mol.family.M} | {mol.complexity:.3f} | {mol.rank} |
| Financial | 252 days, 30 assets | {fin_t:.0f}ms | {fin.family.N} | {fin.family.M} | {fin.complexity:.3f} | {fin.rank} |
| Tabular | 500 rows, 20 features | {tab_t:.0f}ms | {tab.family.N} | {tab.family.M} | {tab.complexity:.3f} | {tab.rank} |
| Mesh | 50 vertices, 40 faces | {mesh_t:.0f}ms | {mesh.family.N} | {mesh.family.M} | {mesh.complexity:.3f} | {mesh.rank} |

## Key observations

- **All 12 adapters** build in under {max(audio_t, img_t, graph_t, text_t, ts_t, video_t, voxel_t, pc_t, mol_t, fin_t, tab_t, mesh_t):.0f}ms
- **complexity** ranges from {min(audio.complexity, img.complexity):.3f} (structured) to {max(graph.complexity, text.complexity):.3f} (full-rank)
- Every adapter exposes identical interface: `.kernel`, `.predict()`, `.inverse()`, `.complexity`
- No preprocessing — raw data in, OperatorFamily out

Generated by `demo_benchmark.py` on {time.strftime('%Y-%m-%d %H:%M')}.
"""
with open(OUT, 'w') as f: f.write(md)
print(f"✓ benchmark_adapters.md written — 12 adapters, max build {max(audio_t, img_t, graph_t, text_t, ts_t, video_t, voxel_t, pc_t, mol_t, fin_t, tab_t, mesh_t):.0f}ms")
