#!/usr/bin/env python3
"""Breakthrough benchmark: sparse PDE spectral queries vs industrial baselines."""
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
import sft


REPORT_DIR = os.environ.get("SFT_BREAKTHROUGH_REPORT_DIR", os.path.join(os.path.dirname(__file__), "reports"))
OUT = os.path.join(REPORT_DIR, "breakthrough_pde_queries.md")
os.makedirs(os.path.dirname(OUT), exist_ok=True)

N = int(os.environ.get("SFT_BREAKTHROUGH_PDE_N", "1200"))
Q = int(os.environ.get("SFT_BREAKTHROUGH_PDE_Q", "2000"))
K = int(os.environ.get("SFT_BREAKTHROUGH_PDE_K", "12"))
MEASURED = int(os.environ.get("SFT_BREAKTHROUGH_BASELINE_QUERIES", "12"))
SEED = 42

rng = np.random.default_rng(SEED)
x = np.linspace(0.0, 1.0, N + 2)[1:-1]
model = sft.physics.schrodinger_1d(x, np.zeros_like(x), max_potential_params=64)
fam = model.family()
queries = 0.002 * rng.standard_normal((Q, fam.M))


def build_matrix(k):
    return fam.build_sparse(k)


eigsh_result, eigsh_ref = sft.benchmarks.run_repeated_eigsh(
    build_matrix, queries, K, max_measured=MEASURED, name="industrial_eigsh_loop"
)
lobpcg_result, lobpcg_ref = sft.benchmarks.run_lobpcg_warm_start(
    build_matrix, queries, K, max_measured=MEASURED
)
sft_result, _ = sft.benchmarks.run_sft_predict_many(fam, queries, eigsh_ref)

best_baseline = min([eigsh_result, lobpcg_result], key=lambda r: r.total_ms)
speed = sft.benchmarks.summarize_speedup(sft_result, best_baseline)
meta = sft.benchmarks.machine_metadata()

rows = sft.benchmarks.markdown_result_table([eigsh_result, lobpcg_result, sft_result])

md = f"""# Breakthrough Benchmark: Sparse PDE Spectral Queries

Workload: 1D sparse Schrödinger operator with local potential perturbations.

## Setup

| Field | Value |
|-------|------:|
| N | {N} |
| Parameters M | {fam.M} |
| Low modes K | {K} |
| Query count Q | {Q} |
| Baseline measured queries | {MEASURED} |
| Python | {meta['python']} |
| CPU count | {meta['cpu_count']} |

Baselines are strong sparse methods: `eigsh` per query and warm-start `lobpcg`.
Baseline totals are extrapolated from measured queries when `Q` is large.

## Results

| Method | Setup ms | Query ms | Total ms | Eigensolves | Memory MB | Median err | Max err | Extrapolated |
|--------|---------:|---------:|---------:|------------:|----------:|-----------:|--------:|:------------:|
{rows}

## Breakthrough Signal

| Metric | Value |
|--------|------:|
| Best baseline | {best_baseline.name} |
| Query speedup | {speed['query_speedup']:.1f}x |
| Total speedup | {speed['total_speedup']:.1f}x |
| Eigensolve reduction | {speed['eigensolve_reduction']:.1f}x |
| SFT max error vs measured eigsh | {sft_result.max_error:.3e} |

Generated by `demo_breakthrough_pde.py` on {time.strftime('%Y-%m-%d %H:%M')}.
"""

with open(OUT, "w") as f:
    f.write(md)
print(f"✓ breakthrough_pde_queries.md written — total_speedup={speed['total_speedup']:.1f}x, max_err={sft_result.max_error:.2e}")
