#!/usr/bin/env python3
"""Breakthrough benchmark: 2D PDE spectral control/query workload."""
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
import sft


REPORT_DIR = os.environ.get("SFT_BREAKTHROUGH_REPORT_DIR", os.path.join(os.path.dirname(__file__), "reports"))
OUT = os.path.join(REPORT_DIR, "breakthrough_pde2d_control.md")
os.makedirs(os.path.dirname(OUT), exist_ok=True)

NX = int(os.environ.get("SFT_BREAKTHROUGH_PDE2D_NX", "32"))
NY = int(os.environ.get("SFT_BREAKTHROUGH_PDE2D_NY", "32"))
Q = int(os.environ.get("SFT_BREAKTHROUGH_PDE2D_Q", "1200"))
K = int(os.environ.get("SFT_BREAKTHROUGH_PDE2D_K", "12"))
M = int(os.environ.get("SFT_BREAKTHROUGH_PDE2D_M", "64"))
MEASURED = int(os.environ.get("SFT_BREAKTHROUGH_BASELINE_QUERIES", "10"))
SEED = 11

rng = np.random.default_rng(SEED)
model = sft.physics.laplacian_grid((NX, NY), max_potential_params=M)
fam = model.family()
queries = 0.001 * rng.standard_normal((Q, fam.M))


def build_matrix(k):
    return fam.build_sparse(k)


eigsh_result, eigsh_ref = sft.benchmarks.run_repeated_eigsh(
    build_matrix, queries, K, max_measured=MEASURED, name="industrial_eigsh_loop"
)
lobpcg_result, _ = sft.benchmarks.run_lobpcg_warm_start(
    build_matrix, queries, K, max_measured=MEASURED
)
sft_result, _ = sft.benchmarks.run_sft_predict_many(fam, queries, eigsh_ref)
best_baseline = min([eigsh_result, lobpcg_result], key=lambda r: r.total_ms)
speed = sft.benchmarks.summarize_speedup(sft_result, best_baseline)

true_k = 0.01 * rng.standard_normal(fam.M)
target = fam.spectrum(true_k, n_eigs=K)
t0 = time.perf_counter()
control = fam.inverse(target, n_eigs=K, steps=8, alpha=0.4, refresh_every=3, method="trust")
control_ms = (time.perf_counter() - t0) * 1000
control_error = float(np.max(np.abs(fam.spectrum(control.k, n_eigs=K) - target)))

rows = sft.benchmarks.markdown_result_table([eigsh_result, lobpcg_result, sft_result])

md = f"""# Breakthrough Benchmark: 2D PDE Spectral Control

Workload: sparse 2D grid Laplacian with local potential controls.

## Setup

| Field | Value |
|-------|------:|
| Grid | {NX} x {NY} |
| N | {fam.N} |
| Parameters M | {fam.M} |
| Low modes K | {K} |
| Query count Q | {Q} |
| Baseline measured queries | {MEASURED} |

## Query Results

| Method | Setup ms | Query ms | Total ms | Eigensolves | Memory MB | Median err | Max err | Extrapolated |
|--------|---------:|---------:|---------:|------------:|----------:|-----------:|--------:|:------------:|
{rows}

## Control Result

| Method | Time ms | Eigensolves | Hessian count | Final spectral error |
|--------|--------:|------------:|--------------:|---------------------:|
| SFT trust inverse | {control_ms:.1f} | {control.eigh_count} | {control.hessian_count} | {control_error:.3e} |

## Breakthrough Signal

| Metric | Value |
|--------|------:|
| Best query baseline | {best_baseline.name} |
| Query speedup | {speed['query_speedup']:.1f}x |
| Total speedup | {speed['total_speedup']:.1f}x |
| Eigensolve reduction | {speed['eigensolve_reduction']:.1f}x |
| SFT max error vs measured eigsh | {sft_result.max_error:.3e} |

Generated by `demo_breakthrough_pde2d_control.py` on {time.strftime('%Y-%m-%d %H:%M')}.
"""

with open(OUT, "w") as f:
    f.write(md)
print(f"✓ breakthrough_pde2d_control.md written — total_speedup={speed['total_speedup']:.1f}x, control_err={control_error:.2e}")
