#!/usr/bin/env python3
"""PDE multigrid spectral convergence demo."""
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
import sft


OUT = os.path.join(os.path.dirname(__file__), "reports", "pde_multigrid.md")
os.makedirs(os.path.dirname(OUT), exist_ok=True)

resolutions = [24, 48, 96]
rows = []
t0 = time.perf_counter()
continuum = 0.5 * np.pi ** 2  # first eigenvalue of -1/2 d^2/dx^2 on [0,1]
for n in resolutions:
    x = np.linspace(0.0, 1.0, n + 2)[1:-1]
    model = sft.physics.schrodinger_1d(x, np.zeros_like(x), max_potential_params=8)
    fam = model.family()
    lam = fam.spectrum(np.zeros(fam.M), n_eigs=4)
    err = abs(float(lam[0]) - continuum)
    rows.append((n, float(lam[0]), err, fam.basis_kind, fam._sparse_mode))
elapsed = (time.perf_counter() - t0) * 1000

hs = np.array([1.0 / (n + 1) for n, *_ in rows])
errs = np.array([err for _, _, err, *_ in rows])
slope = float(np.polyfit(np.log(hs), np.log(np.maximum(errs, 1e-15)), 1)[0])

table = "\n".join(
    f"| {n} | {lam0:.8f} | {err:.2e} | {kind} | {sparse_mode} |"
    for n, lam0, err, kind, sparse_mode in rows
)

md = f"""# PDE Multigrid Spectral Convergence

Real finite-difference Schrödinger operator, sparse partial spectrum, three
grid resolutions.

Continuum target for the first mode: `π²/2 = {continuum:.8f}`.

| N | λ₀ partial eig | error | basis | sparse |
|---:|--------------:|------:|-------|:------:|
{table}

Estimated log-log convergence slope: **{slope:.2f}**.

Runtime: {elapsed:.1f}ms.

Generated by `demo_pde_multigrid.py` on {time.strftime('%Y-%m-%d %H:%M')}.
"""

with open(OUT, "w") as f:
    f.write(md)
print(f"✓ pde_multigrid.md written — slope={slope:.2f}, final_error={errs[-1]:.2e}")
